### PR TITLE
Fix tests + bump deps

### PR DESCRIPTION
**Pull request by axel-angel**

### CODE REVIEW

**Comment by axel-angel** [comment]
We still had underflow issues in sink so we decided that it way be worth a try to upgrade the libs @mpenet

**Comment by mpenet** [comment]
Odd. Make sure there are no concurrent appends, at least that was the issue last time.

**Comment by mpenet** [comment]
it's on clojars

**Comment by axel-angel** [comment]
Thanks. To be continued.

**Pull request merged**
